export const properties = [
  {
    id: 1,
    cover: "/images/condo1.jpg",
    name: "Red Carpet Real Estate",
    location: "210 Zirak Road NewYork",
    category: "For Rent",
    price: "$3,400",
    type: "Apartments",
  },
  {
    id: 2,
    cover: "/images/condo2.jpg",
    name: "Fairmount Properties",
    location: "5698 Nottingham Road NewYork",
    category: "For Sale",
    price: "$2,750",
    type: "Houses",
  },
  {
    id: 3,
    cover: "/images/condo3.jpg",
    name: "The Real Estate Corner",
    location: "5624 Mooker Market London",
    category: "For Rent",
    price: "$2,860",
    type: "Apartments",
  },
  {
    id: 4,
    cover: "/images/condo10.jpg",
    name: "Herringbone Realty",
    location: "5621 Liverpool NewYork",
    category: "For Sale",
    price: "$5,540",
    type: "Apartments",
  },
  {
    id: 5,
    cover: "/images/condo5.jpg",
    name: "Brick Lane Realty",
    location: "210 Montreal Road London",
    category: "For Rent",
    price: "$3,850",
    type: "Houses",
  },
  {
    id: 6,
    cover: "/images/condo11.jpg",
    name: "Banyon Tree Realty",
    location: "210 Tree Hill Road NewYork",
    category: "For Sale",
    price: "$3,742",
    type: "Houses",
  },
  {
    id: 7,
    cover: "/images/condo7.jpg",
    name: "Pasedena Ave",
    location: "210 Firestone Road NewYork",
    category: "For Sale",
    price: "$2,742",
    type: "Houses",
  },
  {
    id: 8,
    cover: "/images/condo8.jpg",
    name: "Palm Harbour",
    location: "742 Evergreen Terrace London",
    category: "For Sale",
    price: "$2,742",
    type: "Apartments",
  },
  {
    id: 9,
    cover: "/images/condo9.jpg",
    name: "Sheraton Villa",
    location: "1313 Mockingbird Lane NewYork",
    category: "For Sale",
    price: "$5,742",
    type: "Apartments",
  },
  {
    id: 10,
    cover: "/images/condo10.jpg",
    name: "Cherry Blossom Villa",
    location: "0001 Cemetery Lane London",
    category: "For Sale",
    price: "$5,742",
    type: "Apartments",
  },
  {
    id: 11,
    cover: "/images/condo11.jpg",
    name: "Beverly Hills",
    location: "4222 Clinton Way NewYork",
    category: "For Sale",
    price: "$2,742",
    type: "Apartments",
  },
  {
    id: 12,
    cover: "/images/condo12.jpg",
    name: "Nottingham Condo",
    location: "12 Grimmauld Place London",
    category: "For Sale",
    price: "$2,742",
    type: "Houses",
  },
];
